services:
  trabalho03-postgres:
    image: postgres:15
    container_name: trabalho03-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: gestao_tarefas
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  trabalho03-linux:
    build: .
    container_name: trabalho03-linux
    depends_on:
      - trabalho03-postgres
    environment:
      DB_HOST: trabalho03-postgres
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: gestao_tarefas
    ports:
      - "8080:80"
    volumes:
      - ./scripts:/app/scripts
      - ./source:/app/source
      - ./logs:/app/logs
      - ./backups:/app/backups

volumes:
  pgdata:
